import dotenv from "dotenv";
dotenv.config();

import connectDB from "../config/db.js";
import Genre from "../models/genre.model.js";
import Movie from "../models/movie.model.js";

const seedMovies = async () => {
  await connectDB();
  console.log("🔍 Checking Movies...");

  const movieCount = await Movie.countDocuments();
  if (movieCount > 0) {
    console.log("⚠️ Movies already exist. Deleting old data...");
    await Movie.deleteMany();
  }

  const genres = await Genre.find();
  if (genres.length === 0) {
    console.log("⚠️ No genres found. Run seedGenres first!");
    process.exit(1);
  }

  const pickRandomGenres = () => {
    const count = Math.max(1, Math.floor(Math.random() * 3) + 1); // 1–3 genres
    const ids = [];
    for (let i = 0; i < count; i++) {
      const g = genres[Math.floor(Math.random() * genres.length)];
      if (!ids.includes(g._id)) ids.push(g._id);
    }
    return ids;
  };

  // ==============================
  // 50 PHIM THẬT (MÔ TẢ RIÊNG)
  // ==============================
  const movieTemplates = [
    {
      title: "Avengers: Endgame",
      description: "Các Avengers còn lại hợp lực lần cuối để đảo ngược thảm kịch mà Thanos gây ra cho vũ trụ.",
      director: "Anthony Russo, Joe Russo",
      actors: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth"],
      duration: 181,
      releaseDate: new Date("2019-04-26"),
      posterUrl: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      trailerUrl: "https://www.youtube.com/embed/TcMBFSGVi1c",
    },
    {
      title: "Inception",
      description: "Một kẻ trộm giấc mơ được giao nhiệm vụ cấy ý tưởng vào tiềm thức của mục tiêu.",
      director: "Christopher Nolan",
      actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
      duration: 148,
      releaseDate: new Date("2010-07-16"),
      posterUrl: "https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
      trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    },
    {
      title: "Interstellar",
      description: "Một nhóm phi hành gia du hành qua hố đen để tìm hành tinh mới cho loài người.",
      director: "Christopher Nolan",
      actors: ["Matthew McConaughey", "Anne Hathaway"],
      duration: 169,
      releaseDate: new Date("2014-11-07"),
      posterUrl: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
      trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    },
    {
      title: "John Wick",
      description: "Một sát thủ huyền thoại tái xuất để báo thù băng nhóm đã cướp đi mọi thứ anh còn lại.",
      director: "Chad Stahelski",
      actors: ["Keanu Reeves"],
      duration: 101,
      releaseDate: new Date("2014-10-24"),
      posterUrl: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
      trailerUrl: "https://www.youtube.com/embed/C0BMx-qxsP4",
    },
    {
      title: "Oppenheimer",
      description: "Câu chuyện về J. Robert Oppenheimer và quá trình phát triển bom nguyên tử trong Thế chiến II.",
      director: "Christopher Nolan",
      actors: ["Cillian Murphy", "Robert Downey Jr."],
      duration: 180,
      releaseDate: new Date("2023-07-21"),
      posterUrl: "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
      trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
    },
    {
      title: "Dune: Part Two",
      description: "Paul Atreides liên minh với người Fremen để trả thù những kẻ đã hủy diệt gia tộc mình.",
      director: "Denis Villeneuve",
      actors: ["Timothée Chalamet", "Zendaya"],
      duration: 166,
      releaseDate: new Date("2024-03-01"),
      posterUrl: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
      trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w",
    },
    {
      title: "Spider-Man: No Way Home",
      description:
        "Peter Parker nhờ Doctor Strange giúp che giấu thân phận, nhưng mọi thứ nhanh chóng vượt khỏi tầm kiểm soát.",
      director: "Jon Watts",
      actors: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
      duration: 148,
      releaseDate: new Date("2021-12-17"),
      posterUrl: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      trailerUrl: "https://www.youtube.com/embed/JfVOs4VSpmA",
    },
    {
      title: "The Dark Knight",
      description: "Batman đối đầu Joker, tên tội phạm điên loạn muốn nhấn chìm Gotham trong hỗn loạn.",
      director: "Christopher Nolan",
      actors: ["Christian Bale", "Heath Ledger"],
      duration: 152,
      releaseDate: new Date("2008-07-18"),
      posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
    },
    {
      title: "The Lord of the Rings: The Return of the King",
      description: "Frodo và Sam tiến gần Mount Doom, trong khi các đồng minh chiến đấu trận cuối chống lại Sauron.",
      director: "Peter Jackson",
      actors: ["Elijah Wood", "Viggo Mortensen"],
      duration: 201,
      releaseDate: new Date("2003-12-17"),
      posterUrl: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      trailerUrl: "https://www.youtube.com/embed/r5X-hFf6Bwo",
    },
    {
      title: "Avatar",
      description: "Một cựu lính thủy đánh bộ tàn tật tham gia chương trình Avatar trên hành tinh Pandora.",
      director: "James Cameron",
      actors: ["Sam Worthington", "Zoe Saldana"],
      duration: 162,
      releaseDate: new Date("2009-12-18"),
      posterUrl: "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
      trailerUrl: "https://www.youtube.com/embed/6ziBFh3V1aM",
    },
    {
      title: "Avatar: The Way of Water",
      description: "Gia đình Jake Sully phải rời bỏ ngôi nhà và tìm nơi trú ẩn mới dưới thế giới đại dương Pandora.",
      director: "James Cameron",
      actors: ["Sam Worthington", "Zoe Saldana"],
      duration: 192,
      releaseDate: new Date("2022-12-16"),
      posterUrl: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
      trailerUrl: "https://www.youtube.com/embed/d9MyW72ELq0",
    },
    {
      title: "Joker",
      description: "Arthur Fleck, một diễn viên hài thất bại, dần trượt dài vào bóng tối và trở thành Joker.",
      director: "Todd Phillips",
      actors: ["Joaquin Phoenix"],
      duration: 122,
      releaseDate: new Date("2019-10-04"),
      posterUrl: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      trailerUrl: "https://www.youtube.com/embed/t433PEQGErc",
    },
    {
      title: "Tenet",
      description: "Một đặc vụ học cách điều khiển thời gian để ngăn chặn thảm họa toàn cầu bí ẩn.",
      director: "Christopher Nolan",
      actors: ["John David Washington", "Robert Pattinson"],
      duration: 150,
      releaseDate: new Date("2020-08-26"),
      posterUrl: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
      trailerUrl: "https://www.youtube.com/embed/LdOM0x0XDMo",
    },
    {
      title: "Mad Max: Fury Road",
      description: "Max hợp tác với Furiosa để giải cứu nhóm phụ nữ khỏi bạo chúa hoang mạc Immortan Joe.",
      director: "George Miller",
      actors: ["Tom Hardy", "Charlize Theron"],
      duration: 120,
      releaseDate: new Date("2015-05-15"),
      posterUrl: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
      trailerUrl: "https://www.youtube.com/embed/hEJnMQG9ev8",
    },
    {
      title: "Black Panther",
      description: "T’Challa trở về Wakanda để nhận ngai vàng và bảo vệ vương quốc khỏi kẻ thù mới.",
      director: "Ryan Coogler",
      actors: ["Chadwick Boseman", "Michael B. Jordan"],
      duration: 134,
      releaseDate: new Date("2018-02-16"),
      posterUrl: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
      trailerUrl: "https://www.youtube.com/embed/xjDjIWPwcPU",
    },
    {
      title: "The Hunger Games",
      description: "Katniss tình nguyện tham gia trò chơi sinh tồn đẫm máu để cứu em gái.",
      director: "Gary Ross",
      actors: ["Jennifer Lawrence"],
      duration: 142,
      releaseDate: new Date("2012-03-23"),
      posterUrl: "https://image.tmdb.org/t/p/w500/1PttgvyguJ1usHHKjNT8iFpyCq1.jpg",
      trailerUrl: "https://www.youtube.com/embed/mfmrPu43DF8",
    },
    {
      title: "Frozen II",
      description: "Elsa và Anna khám phá nguồn gốc sức mạnh băng giá và bí ẩn về vương quốc của họ.",
      director: "Chris Buck, Jennifer Lee",
      actors: ["Idina Menzel", "Kristen Bell"],
      duration: 103,
      releaseDate: new Date("2019-11-22"),
      posterUrl: "https://image.tmdb.org/t/p/w500/qdfARIhgpgZOBh3vfNhWS4hmSo3.jpg",
      trailerUrl: "https://www.youtube.com/embed/bwzLiQZDw2I",
    },
    {
      title: "Inside Out",
      description: "Năm cảm xúc trong đầu một cô bé phải học cách phối hợp khi cuộc sống cô thay đổi.",
      director: "Pete Docter",
      actors: ["Amy Poehler", "Bill Hader"],
      duration: 95,
      releaseDate: new Date("2015-06-19"),
      posterUrl: "https://image.tmdb.org/t/p/w500/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg",
      trailerUrl: "https://www.youtube.com/embed/yRUAzGQ3nSY",
    },
    {
      title: "Coco",
      description: "Cậu bé Miguel lạc vào thế giới người đã khuất để khám phá bí mật gia đình.",
      director: "Lee Unkrich",
      actors: ["Anthony Gonzalez", "Gael García Bernal"],
      duration: 105,
      releaseDate: new Date("2017-11-22"),
      posterUrl: "https://image.tmdb.org/t/p/w500/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
      trailerUrl: "https://www.youtube.com/embed/Cd8t2u5xYQo",
    },
    {
      title: "The Lion King (2019)",
      description: "Simba phải đối mặt với quá khứ để giành lại vị trí vua hợp pháp của mình.",
      director: "Jon Favreau",
      actors: ["Donald Glover", "Beyoncé"],
      duration: 118,
      releaseDate: new Date("2019-07-19"),
      posterUrl: "https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
      trailerUrl: "https://www.youtube.com/embed/lFzVJEksoDY",
    },
    {
      title: "Doctor Strange",
      description: "Một bác sĩ phẫu thuật tài năng học phép thuật để bảo vệ thế giới khỏi thế lực siêu nhiên.",
      director: "Scott Derrickson",
      actors: ["Benedict Cumberbatch", "Rachel McAdams"],
      duration: 115,
      releaseDate: new Date("2016-11-04"),
      posterUrl: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
      trailerUrl: "https://www.youtube.com/embed/Lt-U_t2pUHI",
    },
    {
      title: "Guardians of the Galaxy",
      description: "Một nhóm kẻ lập dị trở thành anh hùng bất đắc dĩ để cứu lấy dải ngân hà.",
      director: "James Gunn",
      actors: ["Chris Pratt", "Zoe Saldana"],
      duration: 121,
      releaseDate: new Date("2014-08-01"),
      posterUrl: "https://image.tmdb.org/t/p/w500/y31QB9kn3XSudA15tV7UWQ9XLuW.jpg",
      trailerUrl: "https://www.youtube.com/embed/d96cjJhvlMA",
    },
    {
      title: "Shang-Chi and the Legend of the Ten Rings",
      description: "Shang-Chi đối mặt quá khứ và gia đình gắn liền với Thập Nhẫn huyền thoại.",
      director: "Destin Daniel Cretton",
      actors: ["Simu Liu", "Awkwafina"],
      duration: 132,
      releaseDate: new Date("2021-09-03"),
      posterUrl: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
      trailerUrl: "https://www.youtube.com/embed/giWIr7U1deA",
    },
    {
      title: "Deadpool",
      description: "Một lính đánh thuê lắm mồm sở hữu khả năng hồi phục đáng kinh ngạc sau thí nghiệm bí mật.",
      director: "Tim Miller",
      actors: ["Ryan Reynolds"],
      duration: 108,
      releaseDate: new Date("2016-02-12"),
      posterUrl: "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
      trailerUrl: "https://www.youtube.com/embed/ONHBaC-pfsk",
    },
    {
      title: "Pokémon Detective Pikachu",
      description: "Một chàng trai hợp tác với Pikachu biết nói để điều tra vụ mất tích kỳ lạ của cha mình.",
      director: "Rob Letterman",
      actors: ["Ryan Reynolds", "Justice Smith"],
      duration: 104,
      releaseDate: new Date("2019-05-10"),
      posterUrl: "https://image.tmdb.org/t/p/w500/wgQ7APnFpf1TuviKHXeEe3KnsTV.jpg",
      trailerUrl: "https://www.youtube.com/embed/1roy4o4tqQM",
    },
    {
      title: "Parasite",
      description: "Một gia đình nghèo dần len lỏi vào nhà gia đình giàu có với những bí mật tăm tối.",
      director: "Bong Joon-ho",
      actors: ["Song Kang-ho", "Choi Woo-shik"],
      duration: 132,
      releaseDate: new Date("2019-05-30"),
      posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      trailerUrl: "https://www.youtube.com/embed/5xH0HfJHsaY",
    },
    {
      title: "Train to Busan",
      description: "Hành khách trên chuyến tàu đến Busan phải đấu tranh sinh tồn trước đại dịch zombie.",
      director: "Yeon Sang-ho",
      actors: ["Gong Yoo", "Ma Dong-seok"],
      duration: 118,
      releaseDate: new Date("2016-07-20"),
      posterUrl: "https://image.tmdb.org/t/p/w500/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg",
      trailerUrl: "https://www.youtube.com/embed/pyWuHv2-Abk",
    },
    {
      title: "Your Name",
      description: "Hai cô cậu xa lạ bất ngờ hoán đổi thân xác và kết nối bằng mối dây kỳ lạ.",
      director: "Makoto Shinkai",
      actors: ["Ryunosuke Kamiki", "Mone Kamishiraishi"],
      duration: 106,
      releaseDate: new Date("2016-08-26"),
      posterUrl: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
      trailerUrl: "https://www.youtube.com/embed/xU47nhruN-Q",
    },
    {
      title: "Spirited Away",
      description: "Cô bé Chihiro lạc vào thế giới linh hồn và phải tìm cách giải cứu bố mẹ.",
      director: "Hayao Miyazaki",
      actors: ["Rumi Hiiragi", "Miyu Irino"],
      duration: 125,
      releaseDate: new Date("2001-07-20"),
      posterUrl: "https://image.tmdb.org/t/p/w500/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg",
      trailerUrl: "https://www.youtube.com/embed/ByXuk9QqQkk",
    },
    {
      title: "Demon Slayer: Mugen Train",
      description: "Tanjiro và đồng đội bảo vệ đoàn tàu trước con quỷ mạnh mẽ phục vụ Muzan.",
      director: "Haruo Sotozaki",
      actors: ["Natsuki Hanae", "Akari Kito"],
      duration: 117,
      releaseDate: new Date("2020-10-16"),
      posterUrl: "https://image.tmdb.org/t/p/w500/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
      trailerUrl: "https://www.youtube.com/embed/bFwdl2PDAFM",
    },
    {
      title: "Titanic",
      description: "Chuyện tình bi thương giữa Jack và Rose trên con tàu định mệnh Titanic.",
      director: "James Cameron",
      actors: ["Leonardo DiCaprio", "Kate Winslet"],
      duration: 195,
      releaseDate: new Date("1997-12-19"),
      posterUrl: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
      trailerUrl: "https://www.youtube.com/embed/CHekzSiZjrY",
    },
    {
      title: "Gladiator",
      description: "Một tướng lĩnh La Mã bị phản bội trở thành đấu sĩ và tìm cách trả thù hoàng đế.",
      director: "Ridley Scott",
      actors: ["Russell Crowe", "Joaquin Phoenix"],
      duration: 155,
      releaseDate: new Date("2000-05-05"),
      posterUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
      trailerUrl: "https://www.youtube.com/embed/P5ieIbInFpg",
    },
    {
      title: "The Godfather",
      description: "Gia đình mafia Corleone đấu tranh giữ quyền lực giữa bạo lực và phản bội.",
      director: "Francis Ford Coppola",
      actors: ["Marlon Brando", "Al Pacino"],
      duration: 175,
      releaseDate: new Date("1972-03-24"),
      posterUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      trailerUrl: "https://www.youtube.com/embed/sY1S34973zA",
    },
    {
      title: "Fight Club",
      description: "Một nhân viên văn phòng lập câu lạc bộ đánh nhau bí mật với kẻ nổi loạn Tyler Durden.",
      director: "David Fincher",
      actors: ["Brad Pitt", "Edward Norton"],
      duration: 139,
      releaseDate: new Date("1999-10-15"),
      posterUrl: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
      trailerUrl: "https://www.youtube.com/embed/SUXWAEX2jlg",
    },
    {
      title: "The Shawshank Redemption",
      description: "Một tù nhân bị kết án oan nuôi hy vọng tự do suốt nhiều thập kỷ trong nhà tù Shawshank.",
      director: "Frank Darabont",
      actors: ["Tim Robbins", "Morgan Freeman"],
      duration: 142,
      releaseDate: new Date("1994-09-23"),
      posterUrl: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
      trailerUrl: "https://www.youtube.com/embed/6hB3S9bIaco",
    },
    {
      title: "The Social Network",
      description: "Câu chuyện hình thành Facebook và những mâu thuẫn pháp lý quanh Mark Zuckerberg.",
      director: "David Fincher",
      actors: ["Jesse Eisenberg", "Andrew Garfield"],
      duration: 120,
      releaseDate: new Date("2010-10-01"),
      posterUrl: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
      trailerUrl: "https://www.youtube.com/embed/lB95KLmpLR4",
    },
    {
      title: "La La Land",
      description: "Chuyện tình giữa nhạc sĩ jazz và nữ diễn viên trẻ giữa hào nhoáng Hollywood.",
      director: "Damien Chazelle",
      actors: ["Ryan Gosling", "Emma Stone"],
      duration: 128,
      releaseDate: new Date("2016-12-09"),
      posterUrl: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
      trailerUrl: "https://www.youtube.com/embed/0pdqf4P9MB8",
    },
    {
      title: "Whiplash",
      description: "Một tay trống trẻ chấp nhận bị huấn luyện tàn bạo để chạm tới sự vĩ đại.",
      director: "Damien Chazelle",
      actors: ["Miles Teller", "J.K. Simmons"],
      duration: 107,
      releaseDate: new Date("2014-10-10"),
      posterUrl: "https://image.tmdb.org/t/p/w500/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg",
      trailerUrl: "https://www.youtube.com/embed/7d_jQycdQGo",
    },
    {
      title: "1917",
      description: "Hai binh sĩ Anh được giao nhiệm vụ nguy hiểm truyền lệnh để cứu hàng nghìn người.",
      director: "Sam Mendes",
      actors: ["George MacKay", "Dean-Charles Chapman"],
      duration: 119,
      releaseDate: new Date("2019-12-25"),
      posterUrl: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
      trailerUrl: "https://www.youtube.com/embed/YqNYrYUiMfg",
    },
    {
      title: "A Quiet Place",
      description: "Một gia đình phải sống trong im lặng tuyệt đối để tránh sinh vật săn bằng âm thanh.",
      director: "John Krasinski",
      actors: ["Emily Blunt", "John Krasinski"],
      duration: 90,
      releaseDate: new Date("2018-04-06"),
      posterUrl: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
      trailerUrl: "https://www.youtube.com/embed/WR7cc5t7tv8",
    },
    {
      title: "The Conjuring",
      description: "Vợ chồng Warren điều tra hiện tượng ma quỷ trong một trang trại hẻo lánh.",
      director: "James Wan",
      actors: ["Patrick Wilson", "Vera Farmiga"],
      duration: 112,
      releaseDate: new Date("2013-07-19"),
      posterUrl: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
      trailerUrl: "https://www.youtube.com/embed/k10ETZ41q5o",
    },
    {
      title: "The Nun",
      description: "Một linh mục và nữ tu tập sự điều tra cái chết bí ẩn tại tu viện Romania.",
      director: "Corin Hardy",
      actors: ["Taissa Farmiga", "Demián Bichir"],
      duration: 96,
      releaseDate: new Date("2018-09-07"),
      posterUrl: "https://image.tmdb.org/t/p/w500/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg",
      trailerUrl: "https://www.youtube.com/embed/pzD9zGcUNrw",
    },
    {
      title: "Annabelle",
      description: "Một con búp bê bị quỷ ám gieo rắc kinh hoàng cho đôi vợ chồng trẻ.",
      director: "John R. Leonetti",
      actors: ["Annabelle Wallis", "Ward Horton"],
      duration: 99,
      releaseDate: new Date("2014-10-03"),
      posterUrl: "https://image.tmdb.org/t/p/w500/lcq8dVxeeOqHvvgcte707K0KVx5.jpg",
      trailerUrl: "https://www.youtube.com/embed/paFgQNPGlsg",
    },
    {
      title: "It",
      description: "Một nhóm trẻ em đối đầu thực thể tà ác mang hình dáng chú hề Pennywise.",
      director: "Andy Muschietti",
      actors: ["Bill Skarsgård", "Jaeden Martell"],
      duration: 135,
      releaseDate: new Date("2017-09-08"),
      posterUrl: "https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
      trailerUrl: "https://www.youtube.com/embed/7no56Zw1e20",
    },
    {
      title: "The Exorcist",
      description: "Một linh mục cố gắng trừ tà cho cô bé bị quỷ Satan chiếm hữu.",
      director: "William Friedkin",
      actors: ["Linda Blair", "Ellen Burstyn"],
      duration: 122,
      releaseDate: new Date("1973-12-26"),
      posterUrl: "https://image.tmdb.org/t/p/w500/5wW6bqB8VafRcaO8EoSnhmm7xQC.jpg",
      trailerUrl: "https://www.youtube.com/embed/YDGw1MTEe9k",
    },
    {
      title: "Minions",
      description: "Những sinh vật vàng ngố tàu đi tìm chủ nhân phản diện mới để phục vụ.",
      director: "Pierre Coffin, Kyle Balda",
      actors: ["Sandra Bullock", "Pierre Coffin"],
      duration: 91,
      releaseDate: new Date("2015-07-10"),
      posterUrl: "https://image.tmdb.org/t/p/w500/q0R4crx2SehcEEQEkYObktdeFy.jpg",
      trailerUrl: "https://www.youtube.com/embed/eisKxhjBnZ0",
    },
    {
      title: "Despicable Me",
      description: "Tên tội phạm Gru lên kế hoạch trộm mặt trăng nhưng bị ba cô bé mồ côi làm lung lay.",
      director: "Pierre Coffin, Chris Renaud",
      actors: ["Steve Carell", "Miranda Cosgrove"],
      duration: 95,
      releaseDate: new Date("2010-07-09"),
      posterUrl: "https://image.tmdb.org/t/p/w500/yWmWadsZuFMRPERTGTrqDqloy16.jpg",
      trailerUrl: "https://www.youtube.com/embed/zzCZ1W_CUoI",
    },
    {
      title: "Toy Story 3",
      description: "Woody và nhóm đồ chơi đối mặt nguy cơ bị bỏ rơi khi Andy lên đại học.",
      director: "Lee Unkrich",
      actors: ["Tom Hanks", "Tim Allen"],
      duration: 103,
      releaseDate: new Date("2010-06-18"),
      posterUrl: "https://image.tmdb.org/t/p/w500/mMltbSxwEdNE4Cv8QYLpzkHWTDo.jpg",
      trailerUrl: "https://www.youtube.com/embed/JcpWXaA2qeg",
    },
    {
      title: "Finding Nemo",
      description: "Marlin vượt đại dương để tìm lại cậu con trai Nemo bị bắt cóc.",
      director: "Andrew Stanton",
      actors: ["Albert Brooks", "Ellen DeGeneres"],
      duration: 100,
      releaseDate: new Date("2003-05-30"),
      posterUrl: "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
      trailerUrl: "https://www.youtube.com/embed/wZdpNglLbt8",
    },
    {
      title: "Up",
      description: "Ông lão góa vợ bay đến Nam Mỹ bằng căn nhà treo bóng, vô tình mang theo một cậu bé hướng đạo.",
      director: "Pete Docter",
      actors: ["Edward Asner", "Jordan Nagai"],
      duration: 96,
      releaseDate: new Date("2009-05-29"),
      posterUrl: "https://image.tmdb.org/t/p/w500/volXfu3Q12FdYhaK0tBDKQpo0Lw.jpg",
      trailerUrl: "https://www.youtube.com/embed/ORFWdXl_zJ4",
    },
  ];

  const moviesToInsert = movieTemplates.map((tpl) => ({
    title: tpl.title,
    slug: tpl.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, ""),
    description: tpl.description,
    duration: tpl.duration,
    releaseDate: tpl.releaseDate,
    director: tpl.director,
    actors: tpl.actors,
    genres: pickRandomGenres(),
    language: "English",
    subtitles: ["Vietnamese"],
    rating: "C16",
    posterUrl: tpl.posterUrl,
    trailerUrl: tpl.trailerUrl,
    status: "Đang chiếu",
  }));

  await Movie.insertMany(moviesToInsert);

  console.log(`🎉 Imported ${moviesToInsert.length} real movies`);
  process.exit(0);
};

seedMovies();
